// Возможные записи в истории болезни: жалоба, диагноз и приём какого врача
export const VISIT_TEMPLATES = [
    { specialty: 'Терапевт', complaint: 'Кашель, насморк, температура 37,5', diagnosis: 'ОРВИ' },
    { specialty: 'Терапевт', complaint: 'Боль в горле, слабость', diagnosis: 'Острый фарингит' },
    { specialty: 'Терапевт', complaint: 'Температура 38,9, ломота в теле', diagnosis: 'Грипп' },
    { specialty: 'Терапевт', complaint: 'Кашель более двух недель', diagnosis: 'Острый бронхит' },
    { specialty: 'Терапевт', complaint: 'Слабость, быстрая утомляемость', diagnosis: 'Железодефицитная анемия' },
    { specialty: 'Терапевт', complaint: 'Справка для бассейна', diagnosis: 'Практически здоров' },
    { specialty: 'Кардиолог', complaint: 'Головные боли, давление 150/95', diagnosis: 'Артериальная гипертензия' },
    { specialty: 'Кардиолог', complaint: 'Перебои в работе сердца, одышка', diagnosis: 'Экстрасистолия' },
    { specialty: 'Кардиолог', complaint: 'Боль за грудиной при нагрузке', diagnosis: 'Стенокардия напряжения' },
    { specialty: 'Невролог', complaint: 'Боль в пояснице, отдаёт в ногу', diagnosis: 'Люмбоишиалгия' },
    { specialty: 'Невролог', complaint: 'Головокружение, шум в ушах', diagnosis: 'Вегетососудистая дистония' },
    { specialty: 'Невролог', complaint: 'Онемение пальцев рук по ночам', diagnosis: 'Туннельный синдром' },
    { specialty: 'Невролог', complaint: 'Мигрень, светобоязнь', diagnosis: 'Мигрень без ауры' },
    { specialty: 'Офтальмолог', complaint: 'Резь в глазах, покраснение', diagnosis: 'Острый конъюнктивит' },
    { specialty: 'Офтальмолог', complaint: 'Плохо вижу вдаль', diagnosis: 'Миопия слабой степени' },
    { specialty: 'Офтальмолог', complaint: 'Сухость и усталость глаз к вечеру', diagnosis: 'Синдром сухого глаза' },
    { specialty: 'Хирург', complaint: 'Боль в колене после падения', diagnosis: 'Ушиб коленного сустава' },
    { specialty: 'Хирург', complaint: 'Нагноение пореза на пальце', diagnosis: 'Панариций' },
    { specialty: 'Хирург', complaint: 'Вросший ноготь, боль', diagnosis: 'Онихокриптоз' },
    { specialty: 'Отоларинголог', complaint: 'Заложенность носа, головная боль', diagnosis: 'Острый гайморит' },
    { specialty: 'Отоларинголог', complaint: 'Боль в ухе, снижение слуха', diagnosis: 'Острый средний отит' },
    { specialty: 'Отоларинголог', complaint: 'Частые ангины', diagnosis: 'Хронический тонзиллит' },
    { specialty: 'Дерматолог', complaint: 'Зудящая сыпь на руках', diagnosis: 'Аллергический дерматит' },
    { specialty: 'Дерматолог', complaint: 'Прыщи на лице и спине', diagnosis: 'Акне средней степени' },
    { specialty: 'Дерматолог', complaint: 'Шелушащиеся пятна на локтях', diagnosis: 'Псориаз' },
    { specialty: 'Эндокринолог', complaint: 'Сильная жажда, частое мочеиспускание', diagnosis: 'Нарушение толерантности к глюкозе' },
    { specialty: 'Эндокринолог', complaint: 'Набор веса, сонливость', diagnosis: 'Гипотиреоз' },
    { specialty: 'Педиатр', complaint: 'Сыпь и температура у ребёнка', diagnosis: 'Ветряная оспа' },
    { specialty: 'Гастроэнтеролог', complaint: 'Изжога после еды, тяжесть в желудке', diagnosis: 'Гастрит' },
    { specialty: 'Гастроэнтеролог', complaint: 'Тошнота, боль в правом подреберье', diagnosis: 'Хронический холецистит' },
    { specialty: 'Уролог', complaint: 'Рези при мочеиспускании', diagnosis: 'Цистит' },
    { specialty: 'Проктолог', complaint: 'Дискомфорт и зуд, кровь после туалета', diagnosis: 'Геморрой' },
    { specialty: 'Травматолог', complaint: 'Боль в запястье после падения на льду', diagnosis: 'Растяжение связок' },
    { specialty: 'Аллерголог', complaint: 'Чихание и слезотечение весной', diagnosis: 'Поллиноз' },
    { specialty: 'Пульмонолог', complaint: 'Одышка при подъёме по лестнице', diagnosis: 'Хроническая обструктивная болезнь лёгких' },
    { specialty: 'Стоматолог', complaint: 'Острая боль в зубе от холодного', diagnosis: 'Кариес' },
];

export const MIN_VISITS = 10;
export const MAX_VISITS = 40;
